### ISSUE TITLE
how do run parallel on Multiple servers ?

### ISSUE THREAD

**Issue by cucy** [hoto/jenkinsfile-examples#1]
some time need run command on Multiple servers; Such as deploy code to servers, i don't want use ansible,pupet...

**Comment by hoto** [comment]
I must have missed this a year ago, sorry about that!
You didn't really supply enough information to give a good answer.
Depends what do you mean by "deploy code".
What is the packaging of the code?
Zip, jar, container?
There are plugins for jenkins which can deal with this kind of stuff if you don't want to setup a tool yourself.
